// <auto-generated />
using System;
using Expense_Service.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Expense_Service.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    [Migration("20220428094540_4")]
    partial class _4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Expense_Service.Models.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "Home",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "Car",
                            Name = "Car"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "Travel",
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "Food",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "TshirtCrewOutline",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "Pill",
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "FuelPump",
                            Name = "Fuel"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "BabyFaceOutline",
                            Name = "Baby"
                        },
                        new
                        {
                            Id = 9,
                            Icon = "QuestionMark",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Expense_Service.Models.Transaction", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<double?>("Amount")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int>("CatagoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.0,
                            CatagoryId = 1,
                            Date = new DateTime(2022, 4, 28, 15, 15, 40, 361, DateTimeKind.Local).AddTicks(5668),
                            Description = "a"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0,
                            CatagoryId = 2,
                            Date = new DateTime(2022, 4, 28, 15, 15, 40, 361, DateTimeKind.Local).AddTicks(5680),
                            Description = "a"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
