// <auto-generated />
using System;
using Income_Service.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Income_Service.Migrations
{
    [DbContext(typeof(IncomeDbContext))]
    [Migration("20220428055229_9")]
    partial class _9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Income_Service.Models.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "Home",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "Dollar",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "QuestionMark",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Income_Service.Models.Transaction", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<double?>("Amount")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int>("CatagoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.0,
                            CatagoryId = 1,
                            Date = new DateTime(2022, 4, 28, 11, 22, 28, 819, DateTimeKind.Local).AddTicks(9118),
                            Description = "a"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0,
                            CatagoryId = 2,
                            Date = new DateTime(2022, 4, 28, 11, 22, 28, 819, DateTimeKind.Local).AddTicks(9131),
                            Description = "a"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
