// <auto-generated />
using System;
using Income_Service.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Income_Service.Migrations
{
    [DbContext(typeof(IncomeDbContext))]
    [Migration("20220429130321_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Income_Service.Models.Catagory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Catagories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "Home",
                            Name = "Home"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "Dollar",
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "QuestionMark",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Income_Service.Models.Transaction", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<double?>("Amount")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int>("CatagoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CatagoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.0,
                            CatagoryId = 1,
                            Date = new DateTime(2022, 4, 29, 18, 33, 21, 222, DateTimeKind.Local).AddTicks(9532),
                            Description = "a"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 100.0,
                            CatagoryId = 2,
                            Date = new DateTime(2022, 4, 29, 18, 33, 21, 222, DateTimeKind.Local).AddTicks(9544),
                            Description = "a"
                        });
                });

            modelBuilder.Entity("Income_Service.Models.Transaction", b =>
                {
                    b.HasOne("Income_Service.Models.Catagory", "Catagory")
                        .WithMany("Transactions")
                        .HasForeignKey("CatagoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catagory");
                });

            modelBuilder.Entity("Income_Service.Models.Catagory", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
